package lk.ijse.mental_hospital.enumaration;

public enum DoctorSpecialization {
    PSYCHIATRIST,
    CLINICAL_PSYCHOLOGIST,
    COUNSELING_PSYCHOLOGIST,
    CHILD_AND_ADOLESCENT_PSYCHIATRIST,
    GERIATRIC_PSYCHIATRIST,
    ADDICTION_PSYCHIATRIST,
    FORENSIC_PSYCHIATRIST,
    NEUROPSYCHIATRIST,
    PSYCHOTHERAPIST,
    BEHAVIORAL_THERAPIST,
    OCCUPATIONAL_THERAPIST,
    PSYCHIATRIC_NURSE,
    SOCIAL_WORKER,
    FAMILY_THERAPIST

}
